export const questions_en = ["If you had all the time in the world, what would you do?",
"If you had to eat one dish all day, what would it be?",
"If you could do it again this week, what would you do differently",
"If you could travel through time, what time would you like to travel to?",
"If you could change one thing from your past what would it be?",
"If you started your own business, what would you sell?",
"If you had a crystal ball, what would you like to see in it?",
"If you were a superhero, who would you be?",
"If you could be anyone else, who would you want to be?",
"If you could say one thing to the world, what would it be?",
"If you could only watch one more series, which one would you choose?",
"If you were immortal for 1 day, what would you do?",
"If you could go back in time, what would you do?",
"If you could choose your own name, what would it be?",
"What animal would you like to reincarnate as?",
"Are you superstitious?",
"Are you a dreamer, thinker or doer?",
"Are you a pessimist or an optimist?",
"Are you happy?",
"Would you rather be tall and fat, or short and athletic?",
"Would you rather be popular or would you rather be smart?",
"Have you ever been to the emergency room?",
"Are you an outdoors person - or an indoor person?",
"Are you a morning or an evening person?",
"Are you an early bird or an evening person?",
"When playing which game do you always lose?",
"Which movie last made you cry?",
"Which building would you like to take a look inside?",
"Who can you vent your heart to?",
"With whom do you find peace?",
"Do you think aliens will land one day?",
"Who recently surprised you?",
"Do you dare to follow your dreams?",
"Would you rather go to the sun or to the snow?",
"Do you ever lend a helping hand to strangers?",
"Do you believe in love at first sight?",
"Do you believe in coincidence?",
"Did you learn anything new last week?",
"Do you have a safe word?",
"Did you meet someone this year who changed your life?",
"Would you rather have no TV for a year or no snacks for a year?",
"Would you rather answer your greatest question or fulfill your greatest wish?",
"Have you ever done anything that got you into trouble?",
"Did you compliment today?",
"Did you get a compliment today?",
"Did you tell a white lie today?",
"How important is Social Media to you?",
"How have you changed in the past five years?",
"How do you think others see you when they first meet you?",
"How do you think a writer would describe you in a novel?",
"How did you meet your first love?",
"How do you charge yourself?",
"How do you show that you love someone?",
"How long have you ever been awake in a row?",
"How are you known to your friends?",
"How do you get up in the morning?",
"How do you put someone else in the spotlight?",
"How are you feeling today?",
"What will the world look like in 10 years?",
"What does your ideal day off look like?",
"What does your dream house look like?",
"What does your ideal holiday look like?",
"What does your morning ritual look like?",
"What does your perfect day look like?",
"What does your perfect date look like?",
"What does your distant future look like?",
"What would your day be like if you were a millionaire?",
"How many pairs of shoes do you have?",
"How many steps do you take in a day?",
"How much time do you spend with your family?",
"How many hours a day do you spend on social media?",
"Do you prefer dogs or cats?",
"Do you prefer sweet or savory?",
"Which book would you like to be the main character in?",
"Which country would you most like to live in?",
"What era would you like to live in?",
"What era would you like to live in?",
"Which TV show would you like to appear in?",
"What century would you like to live in?",
"What sport would you like to be an Olympic athlete in?",
"Do you opt for a city trip or beach holiday?",
"Do you opt for an extensive breakfast or an extensive dinner?",
"Do you prefer to cook yourself or do you prefer to order food?",
"Can you think of a new tea flavor?",
"Prefer 1 year ahead or 1 year back?",
"Prefer to cook or order food?",
"Can you turn off your phone for a day?",
"Would you rather go for a walk in the woods or on the beach?",
"Does Money Make Happy?",
"Which famous person would you like to swap places with for a day?",
"Which family member would you like to trade places with for a day?",
"Which 5 photos would you describe your life with?",
"Which celebrity would you like to have a cup of tea with?",
"Which old friend would you like to meet again?",
"Who haven't you caught up with in a long time?",
"Who was the last person you contacted via Whatsapp?",
"Who do you need to meet again soon?",
"Who do you prefer to celebrate your birthday with?",
"Who do you want to have a quick cup of tea with?",
"Who would you like to trade places with for a day?",
"Who would you like to travel the world with?",
"Who would you most like to drink this cup of tea with?",
"Who would you like to spend 24 hours with?",
"Who would you like to trade with for a day?",
"Which day in history would you like to go back to?",
"Who would you most like to live next to?",
"Name one weird thing about yourself?",
"Who made you laugh the hardest?",
"What's the best way to rest?",
"What unanswered question would you like an answer to?",
"At what time is tea indispensable for you?",
"Who do you look up to?",
"What little things bring you happiness?",
"Which book would you like to see a movie adaptation of?",
"What blunder do you still have nightmares about?",
"Which teacher have you learned the most from?",
"What event did you learn the most from?",
"What event would you like to witness?",
"What little things do you enjoy the most?",
"What little things make you happy?",
"Who did you have a poster of above your bed?",
"Who gave you butterflies in your stomach?",
"Who would you like to read the mind of?",
"Who do you want to spend more time with?",
"Who would you start a fan club for?",
"What are you thankful for?",
"What are you grateful for in life?",
"What are you most afraid of?",
"What are you most grateful for?",
"What are you most proud of?",
"What are you most proud of?",
"What do you spend the most time on on a day off?",
"Where do you prefer to drink a cup of tea?",
"What are you spending too much money on?",
"What do you have no patience for?",
"What was the last thing you took a picture of?",
"What do you regret most?",
"What did you laugh about today?",
"What did you enjoy most last week?",
"What do you look for first in a man/woman?",
"What are you looking forward to this week?",
"What can't you live without?",
"What can you really enjoy?",
"What can you take more time for?",
"What gives you the most energy?",
"What can I wake you up at night for?",
"What do you like to talk about?",
"What are you most ashamed of?",
"What bothers you quickly?",
"Where in the world do you feel most comfortable?",
"Where would you fly if you were a pilot for 1 day?",
"Where do you feel most comfortable?",
"Where do you feel at home?",
"What were you most grateful for last week?",
"What made you happy as a child?",
"What makes you happy?",
"What gets you excited?",
"Where do you see yourself in five years?",
"What would you like to be famous for?",
"Where would you prefer to shop for 10 minutes for free?",
"Where would you like to go on vacation tomorrow?",
"What would you like to be much better at?",
"What would you like to have free access to for a year?",
"What would you like to spend more time on?",
"Why is it nice to have you as a friend?",
"What did you often get into trouble for?",
"When was the last time you wrote a letter by hand?",
"When was the last time you cried with laughter?",
"When was the last time you cried?",
"When was the last time you did something new?",
"When was the last time you challenged yourself?",
"When will the child in you resurface?",
"When do you take a moment for yourself?",
"When do you feel at home somewhere?",
"When do you feel most energetic?",
"When do you think someone is old?",
"When was the last time you were proud of yourself?",
"Was there a day you cried with happiness?",
"What was your favorite thing to eat when you were little?",
"What does relaxing mean to you?",
"What brings a smile to your face?",
"What do you prefer to do on a rainy day?",
"What do you prefer to do on the weekend?",
"What do you like to do most in your spare time?",
"What do you do before going to bed to get a good night's sleep?",
"What do you prefer to eat for breakfast?",
"What do you prefer to eat on your sandwich?",
"What gives you energy?",
"What have you always wanted to learn?",
"What have you always wanted to say to your ex?",
"What's the last thing you bought?",
"What did you take from your parents?",
"What inspires you?",
"What's the best lesson you learned from making a mistake?",
"What's the biggest gamble you've ever taken?",
"What's the biggest prize you've ever won?",
"What's the last dream you remember?",
"What's the last movie you saw?",
"What's the best vacation you've ever had?",
"What's the funniest joke you've ever heard?",
"What's the weirdest place you've ever slept?",
"What is the best childhood memory?",
"What is the most beautiful place you have ever visited?",
"What's the name of your favorite stuffed animal?",
"What's the perfect snack for tea?",
"What's the weirdest dream you've ever had?",
"What is a quality that people don't know about you yet?",
"What's a crazy quality of yours?",
"What is a good quality of yours?",
"What's the most adventurous thing you've ever done?",
"What's the best advice you've been given?",
"What's the best advice you've ever received?",
"What's the first thing you do when you get up?",
"What's the best time of the day?",
"What's the craziest thing you'd like to do?",
"What's the craziest thing you've ever done?",
"What's the craziest thing you've done today?",
"What's the craziest thing you've seen today?",
"What's the last compliment you gave?",
"What's the last thing you do before going to sleep?",
"What's the best party you've ever been to?",
"What's the best thing you learned from your grandmother?",
"What's the nicest thing anyone has ever done for you?",
"What's the sweetest thing you've ever done for someone?",
"What is the most played song in your playlist?",
"What's the most special thing someone has ever done for you?",
"What's the most useless advice you've ever been given?",
"What's the most romantic thing that happened to you?",
"What's the hardest thing you've ever done?",
"What's the best gift you've ever received?",
"What's the best compliment you've received?",
"What is the most beautiful place in the Netherlands?",
"What's the naughtiest thing you've ever done?",
"What's the worst gift you've ever received?",
"What's the stupidest thing you've ever done?",
"What is something that no one knows about you yet?",
"What is something that nobody knows about you yet?",
"What is something that few people know about you?",
"What is your very first memory?",
"What's been your craziest side job?",
"What is your dream job?",
"What's your worst nightmare?",
"What's your favorite holiday?",
"What's your favorite 'wrong' song?",
"What's your favorite dish?",
"What's your favorite quote?",
"What's your favorite candy?",
"What's your favorite game?",
"What is your favorite mode of transport?",
"What's your favorite question to ask?",
"What is your biggest dream?",
"What is your most favorite piece of clothing?",
"What's your least favorite job you've ever had?",
"What is your evening ritual?",
"What is your purpose in life?",
"What's your favorite app?",
"What's your favorite book?",
"What's your favorite day of the week?",
"What is your favorite day of the year?",
"What's your favorite drink?",
"What's your favorite holiday?",
"What is your favorite genre of books?",
"What's your favorite memory?",
"What's your favorite ice cream flavor?",
"What's your favorite me-time moment?",
"What's your favorite song from last month?",
"What is your favorite place in the house?",
"What's your favorite season?",
"What's your favorite season of the year?",
"What's your favorite game?",
"What is your favorite sport?",
"What's your favorite fairy tale?",
"What's your favorite tea moment?",
"What is your favorite holiday country?",
"What is your favorite mode of transport?",
"What's your craziest nickname?",
"What is your greatest achievement?",
"What is your greatest wish?",
"What is your most precious possession?",
"What's your favorite place?",
"What is your most cherished place on earth?",
"What is your best childhood memory?",
"What is your best memory with your family?",
"What's your morning ritual?",
"What is your strongest sense?",
"What is your talent?",
"What is your ultimate moment of happiness?",
"What is important to you in a relationship?",
"What is the best feeling in the world for you?",
"What can really move you?",
"What did you buy with your first paycheck?",
"What can you easily do for hours on end?",
"What is love to you?",
"What makes you special?",
"What makes you unique?",
"What makes your house a home?",
"What do you miss about being a kid?",
"What should remain as it is now?",
"What motivates you?",
"What's always in your fridge?",
"What's still on your bucket list?",
"What's on your wish list?",
"What's in your favorite photo?",
"What do you always procrastinate?",
"What puts a smile on your smile",
"What do you think is the most important thing in life?",
"What do you like most about being a man/woman?",
"What do you think is your best quality?",
"What's the last music you listened to?",
"What do you value in others?",
"What do you value most in friendship?",
"What was your dream job as a child?",
"When was the last time you had the giggles?",
"What was the happiest day of your life?",
"What was the first thing on your mind this morning?",
"What was the last thing on your mind yesterday?",
"What was your biggest blunder?",
"What was your first part-time job?",
"What was your favorite TV show when you were little?",
"What was your best adventure?",
"What was a life-changing experience for you?",
"What do you want to achieve this week?",
"What do you want to do differently today than yesterday?",
"What do you want to have achieved for your next birthday?",
"What did you want to be when you were little?",
"What are three positive things about this day?",
"What are your hidden talents?",
"What would be in the first chapter of your biography?",
"What could you absolutely not miss?",
"What would you do first if you won the lottery?",
"What would you do if you could make a career switch?",
"What would you doif you could spend 1,000 euros one day?",
"What would you do if you were king for a day?",
"What would you do if you never had to work again?",
"What would you do if you were invisible?",
"What would you do if you could switch sex for 1 day?",
"What would you do if you were a kid again for one day?",
"What would you do with 10 million?",
"What would you do with an extra day in the week?",
"What would you do when you woke up and anything was possible?",
"What would you like to do again?",
"What would you buy with your last five euros?",
"What would be your last supper?",
"What would you like to learn again?",
"What else would you most like to ask someone?",
"What would you like to do one day that you've never done before?",
"What would you invent if everything was achievable?",
"What would you wish if you had three wishes?",
"What would you like to change in the world?",
"What would you most like to say to your younger self?",
"What would you change if you were president?",
"What advice would you give your younger self?",
"Which famous person would you like to be one day?",
"What profession would you like to practice for a day?",
"Which profession would you like to try for a week?",
"Which profession would you choose if you could become anything?",
"Which book did you read last?",
"What compliment can you give yourself today?",
"What detail of today do you want to remember?",
"Which animal best represents your character?",
"Which animal best reflects your personality?",
"What animal would you like to be for a day?",
"What goal do you want to achieve this year?",
"Which fictional character would you like to bring to life?",
"What secret does hardly anyone know about you?",
"Which dish did you cook yourself for the first time?",
"Which dish do you like?",
"What New Year's Resolution do you have?",
"What song reminds you of your childhood?",
"Which song do you take to a desert island?",
"Which song brings back special memories?",
"Which musical instrument would you like to learn to play?",
"Which song would you sing at a karaoke night?",
"What positive news from this week has stayed with you?",
"Which Cartoon Character Is Like You?",
"What talent would you like to have?",
"What television program do you refuse to watch?",
"What subject do you think is missing in school?",
"What story do your friends always tell about you?",
"Which 3 teas do you prefer to drink?",
"What 3 items would you take to a desert island?",
"What 3 words best describe you?",
"Which actor would star in the movie about your life?",
"What everyday things make you happy?",
"Which award would you like to win?",
"Which celebrity have you ever met?",
"Which celebrity would you like to be?",
"Which board games are in your top three?",
"What nickname would you give yourself?",
"Which culture fascinates you?",
"Which day would you like to experience again?",
"Which dream has already come true?",
"What dream would you most like to see come true?",
"Which holiday treat should be available all year round?",
"Which movie really impressed you?",
"Which movie have you seen more than 10 times?",
"What gift would you like to have?",
"Which scent evokes a memory from your childhood?",
"What habit would you like to break?",
"What chance do you want to seize again?",
"What character trait would you like to have?",
"Which cuisine do you like best?",
"Which countries have you visited?",
"What age would you most like to be forever?",
"What life lesson do you want to pass on to others?",
"What songs are in the soundtrack of your life?",
"What music touches you?",
"What name would you give yourself if you could change this one?",
"Which planet would you most like to visit?",
"Which place in the world do you want to go to?",
"Which rule would you most like to break?",
"Which games do you prefer to play?",
"Which stamps would you like in your passport?",
"Which superpower would you most like to have?",
"Which language would you like to speak?",
"Which language would you like to learn?",
"What title would you give the book about your life?",
"What traditions do you have in your family?",
"What challenge would you like to take on again?",
"What items from your house would you take with you in a fire?",
"What question would you put on a tea label?",
"Who at this table is the luckiest?",
"Who do you call for a nice evening out?",
"Who always offers you a listening ear?",
"Who brightens you up on a gloomy day?",
"Who did you call last?",
"Who has had the most influence on your life?",
"Who taught you a lot?",
"Who inspires you?",
"Who inspires you to be a better person?",
"Who is the biggest tea lover you know?",
"Who's the last person you thought about yesterday?",
"Who is the nicest person you've met in the past year?",
"Who is an example figure for you?",
"Who is your biggest example?",
"Who is your personal hero?",
"Who is your favorite artist right now?",
"Who knows you best?",
"Who makes you happy?",
"Who always makes you laugh?",
"Who makes you happy?",
"Who should you visit again?",
"Who do you take to a desert island?",
"Who is always there for you?",
"Who from the past would you like to meet?",
"Who do you trust the most?",
"Who do you think was the most annoying teacher at school?",
"Who was your first love?",
"Who do you want to get to know better?",
"Who would you like to personally thank?",
"Who would you take to the moon?",
"Who should give you more compliments?",
"Who could help you today?",
"Who would you like to be for a day?",
"Do you want to continue living where you live now?",
"Would you rather live in a city or a village?",
"Do you ever sing in the shower?",
"Would you rather be in jail or would you rather be homeless?",
"What 3 things can you not live without?",
"Would you like to live abroad?",
"Would you rather live by the sea or in the mountains?",
"Would you rather eat all your food raw or fry all your food?",
"Would you rather win the lottery or find the perfect job?",
"Would you rather be able to read minds or be invisible?",
"Would you rather be able to sing well or dance well?",
"Would you rather be very musical or good at writing?",
"Would you rather change the past or see the future?",
"Would you rather be able to fly or travel through time?",
"Would you rather be rich or rather famous?",
"Would you rather be a king for a day or a child for a day?",
"Would you like to live on Mars if you could?",
"Would you like to live ten years shorter in exchange for being rich?",
"Would you like to be the opposite sex for a day?"];