questions_en = ["If you had all the time in the world, what would you do?",
"If you had to eat one dish all day, what would it be?",
"If you could do it again this week, what would you do differently",
"If you could travel through time, what time would you like to travel to?",
"If you could change one thing from your past what would it be?",
"If you started your own business, what would you sell?",
"If you had a crystal ball, what would you like to see in it?",
"If you were a superhero, who would you be?",
"If you could be anyone else, who would you want to be?",
"If you could say one thing to the world, what would it be?",
"If you could only watch one more series, which one would you choose?",
"If you were immortal for 1 day, what would you do?",
"If you could go back in time, what would you do?",
"If you could choose your own name, what would you call it?",
"What animal would you like to reincarnate as?",
"Are you superstitious?",
"Are you a dreamer, thinker or doer?",
"Are you a pessimist or an optimist?",
"Are you happy?",
"Would you rather be tall and fat, or short and athletic?",
"Would you rather be popular or would you rather be smart?",
"Have you ever been to the emergency room?",
"Are you an outdoors person - or an indoor person?",
"Are you a morning or an evening person?",
"Are you an early bird or an evening person?",
"When playing which game do you always lose?",
"Which movie last made you cry?",
"Which building would you like to take a look inside?",
"Who can you vent your heart to?",
"With whom do you find peace?",
"Do you think aliens will land one day?",
"Who recently surprised you?",
"Do you dare to follow your dreams?",
"Would you rather go to the sun or to the snow?",
"Do you ever lend a helping hand to strangers?",
"Do you believe in love at first sight?",
"Do you believe in coincidence?",
"Did you learn anything new last week?",
"Do you have a safe word?",
"Did you meet someone this year who changed your life?",
"Would you rather have no TV for a year or no snacks for a year?",
"Would you rather answer your greatest question or fulfill your greatest wish?",
"Have you ever done anything that got you into trouble?",
"Did you compliment today?",
"Did you get a compliment today?",
"Did you tell a white lie today?",
"How important is Social Media to you?",
"How have you changed in the past five years?",
"How do you think others see you when they first meet you?",
"How do you think a writer would describe you in a novel?",
"How did you meet your first love?",
"How do you charge yourself?",
"How do you show that you love someone?",
"How long have you ever been awake in a row?",
"How are you known to your friends?",
"How do you get up in the morning?",
"How do you put someone else in the spotlight?",
"How are you feeling today?",
"What will the world look like in 10 years?",
"What does your ideal day off look like?",
"What does your dream house look like?",
"What does your ideal holiday look like?",
"What does your morning ritual look like?",
"What does your perfect day look like?",
"What does your perfect date look like?",
"What does your distant future look like?",
"What would your day be like if you were a millionaire?",
"How many pairs of shoes do you have?",
"How many steps do you take in a day?",
"How much time do you spend with your family?",
"How many hours a day do you spend on social media?",
"Do you prefer dogs or cats?",
"Do you prefer sweet or savory?",
"Which book would you like to be the main character in?",
"Which country would you most like to live in?",
"What era would you like to live in?",
"What era would you like to live in?",
"Which TV show would you like to appear in?",
"What century would you like to live in?",
"What sport would you like to be an Olympic athlete in?",
"Do you opt for a city trip or beach holiday?",
"Do you opt for an extensive breakfast or an extensive dinner?",
"Do you prefer to cook yourself or do you prefer to order food?",
"Can you think of a new tea flavor?",
"Prefer 1 year ahead or 1 year back?",
"Prefer to cook or order food?",
"Can you turn off your phone for a day?",
"Would you rather go for a walk in the woods – or a walk on the beach?",
"Does Money Make Happy?",
"Which famous person would you like to swap places with for a day?",
"Which family member would you like to trade places with for a day?",
"Which 5 photos would you describe your life with?",
"Which celebrity would you like to have a cup of tea with?",
"Which old friend would you like to meet again?",
"Who haven't you caught up with in a long time?",
"Who was the last person you contacted via Whatsapp?",
"Who do you need to meet again soon?",
"Who do you prefer to celebrate your birthday with?",
"Who do you want to have a quick cup of tea with?",
"Who would you like to trade places with for a day?",
"Who would you like to travel the world with?",
"Who would you most like to drink this cup of tea with?",
"Who would you like to spend 24 hours with?",
"Who would you like to have a relationship with?"];